### ISSUE TITLE
specl(): Proposed function definition for SPEC-ACTIONS 

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HSPsquared#13]
propose at https://github.com/respec/HSPsquared/issues/90

- `def specl(io_manager, siminfo, ui, ts, state, specl_actions)`:
  - `io_manager`: global facility to pull data.  Minimize calls to `io_manager` within loops if possible for speed
  - `siminfo`: global info like start, end, timestep other?
  - `ui`: uci data for current block, ie rchres/hydr (verify this path in the Data Dictionary)
  - `ts`: timeseries/[block], ie timeseries/rchres
  - `state`: `ts[step -1]`; the state array for the domain (i.e. RCHRES variables), this is crucial as state variables in the code are simply named variables, not a member of an array, thus difficult to pass into a routine such as `specl()`, however, all values that are relevant should be set at the end of each timestep in the `ts` dictionary, so, passing the last state is both a reasonable way of insuring that only the values that *should* be public are passed, and that the expected state of the system at the last time step is what special actions are acting upon. 
    - Question: does setting a value in the state dictionary propagate back to the variable in the calling loop that contains that state?
  - `specl_actions`: local reach SAs (could be global list of SAs), and `objects` 
    - this can be acquired from `io_manager` in the calling routine prior to looping, so that we avoid redundant data retrievals.
    - propose `get_specl()` in the manner of `get_timeseries()` see [def get_timeseries](https://github.com/respec/HSPsquared/blob/f9555f2e48cc3409f33c29d3c6504d9bdc0f91fb/HSP2/utilities.py#L251)
- Old version hspf used `SUBROUTINE SPECL`, 
- convention in new model is to code wrapper function python equivalents as `[old hspf fn]`, which receives data at each time step then calls python equivalent to old function `_[old hspf function name in lower case]_`
  - Ex: `define hydr()` calls `_hydr_()` [see HYDR.py](https://github.com/respec/HSPsquared/blob/8176be9236be9ee6e55422d01531591a769a8df7/HSP2/HYDR.py#L122)

**Comment by jdkleiner** [comment]
### work session 9/7/22

- def _hydr_(ui, ts, COLIND, OUTDGT, rowsFT, funct, Olabels, OVOLlabels, specactions):
- def specl(uci, ts, step, specactions):
- def _specl_(uci, ts, step, specactions):

**Comment by jdkleiner** [comment]
### HSP2 flowchart (incomplete)
![HSP2_flowchart_2](https://user-images.githubusercontent.com/29379385/190010120-f03febb7-8f6f-45e0-8198-7622abbbeef9.png)


### Questions:
- I'm having trouble loading any modules on deq1 (deq3)
   - pandas, h5py etc. 
   - spent time adjusting where python looks for the python/module installation
- Where do the different model objects come in to the sequence? https://github.com/HARPgroup/HSPsquared/issues/7
- When does the demand() function come into play? (located in HYDR.py)
- Is OUTDGT different from the withdrawal parameter that will be in the `specactions` dictionary?
- Where will the parser come into the sequence?
- Is the HARP hydr CSV the input to `specactions = {}`? https://github.com/HARPgroup/HARParchive/issues/536#issuecomment-1245729144
- Would be good to have an easy way to visualize model results of test runs (using one of the HARP scripts): https://github.com/HARPgroup/HARParchive/issues/505

**Comment by rburghol** [comment]
Let's tackle these in tomorrow's work sesh!
